language: java
before_install:
- curl https://raw.github.com/liveSense/all/master/travis-settings.xml --create-dirs
  -o target/travis/settings.xml
jdk:
- openjdk6
script:
- mvn deploy --settings target/travis/settings.xml
env:
  global:
  - secure: KgFjoAArNx5BXbYb0ew28F6cHnbyqp2h7RQB76jkwtxKUOSh7XLCMj0kzTTU4juDFFtsXMgdFyAjohg/aTLkvhiJij9+FvtDa+esQtbt5apJqyJMA0PCvWG2SR7iJ+wlrD0emX7UrigjCZ6jEU2gkXIngtfiDJk4yJK+uHSXuUk=
  - secure: kXHUdmF6ff/QfBciKB7sH9hang2RcwaS3atv51oJzxGKVDx6X20MHPe0AyPo9fs0xnpOr5/41QcsHHAhtSNEalHH+/4fIbnryXhh60QN1bb+zX83YmAdB+fDsHSJbIFluYvmQ7erjbLKUS8CvJ6SVPXvumhGJxaObnPLI//RNR8=
